apiVersion: v1
kind: Pod
metadata:
        name: client-pod
        labels:
                component: web
spec:
        containers:
                - name: client
                  image: alexbh/catnip
                  ports:
                        - containerPort: 3000
                        
